InternalError = "由于一些内部错误，请求处理失败，请稍后重试。"
DeprecatedURI = "访问的 URI 已经弃用。"
MalformedJSON = "JSON 格式错误。"
AuthError = "账号或密码错误，请重新输入。"
InvalidToken = "Token 验证失败，请重新登录。"
Asynchronization = "异步处理中，请稍后重试。"
InvalidParameter = "参数值校验不通过。"
RequestTimeout = "请求超时，请稍后重试。"
InvalidParameterLength = "{{.Name}} 必须在 0 - {{.MaxLength}} 字符之间。"
ParametherNotAllowedEmpty = "参数 {{.Name}} 不允许为空。"
InvalidParameterValue = "参数 {{.Name}} 值校验不通过。"
InappropriateJSON = "JSON 值校验不通过。"
NotFound = "按条件查询没找到"

[MyUnreadEmails]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."

[PersonUnreadEmails]
description = "The number of unread emails a person has"
one = "{{.Name}} has {{.UnreadEmailCount}} unread email."
other = "{{.Name}} has {{.UnreadEmailCount}} unread emails."
